name: Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Setup
        run: |
          gem install bundler
          bundle install --jobs=3 --retry=3
      - name: Run rubocop
        run: bundle exec rubocop

  build:
    runs-on: ubuntu-latest
    needs: rubocop
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
    name: Ruby ${{ matrix.ruby }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install and Build
        run: |
          gem install bundler
          bundle install --jobs=3 --retry=3
          bundle exec rake test
